name: Build FrpRecorder

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  WEBRTC_URL: https://github.com/elesos/webrtc/blob/master/google-webrtc-1.0.32006.aar
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production  # 可选，不加也可以

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #  安装 Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: 26.1.10909185 # 可选

       # 设置 JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      #- name: Get WEBRTC
      #  run: |
       #   curl -L -o app/libs/google-webrtc-1.0.32006.aar env.WEBRTC_URL
          # 可选：验证文件是否下载成功
        #  ls -la app/libs/
      - name: Download AAR from Release
        uses: robinraju/release-downloader@v1.12
        with:
          repository: "Tonykx2009/FrpRecorder"
          tag: "webrtc-1.0.32006"
          fileName: "google-webrtc-1.0.32006.aar"
          out-file-path: "app/libs"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 编译出未签名包
      - name: Assemble release unsigned APK
        run: ./gradlew assembleRelease

      # 官方工具自动签名（不会出现base64换行/解码失败）
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      # 上传最终可安装的签名包
      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: WebRTCRecorder-Signed
          path: ${{steps.sign_app.outputs.signedFile}}

      
